# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Install build dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       build-essential libjpeg-dev zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY pyproject.toml uv.lock ./
COPY src ./src
COPY README.md ./

# Install project and dependencies
RUN pip install --no-cache-dir hatchling \
    && pip install --no-cache-dir . \
    && rm -rf /root/.cache/pip

# Default entrypoint
ENTRYPOINT ["dwf-analyzer-mcp"]
